### ISSUE TITLE
Misc issues due to re-architecturing

### ISSUE THREAD

**Issue by ugurdogrusoz** [iVis-at-Bilkent/sbgnviz.js-sample-app#1]
- Toolbar:
    o missing tool for Show Selected

- It doesn't open up with the default network fit in window! (Windows 10, Chrome)

- In Dialogs such as Properties and Layout Properties, can we change title and bottom bar background to our default blue color for consistency?

**Comment by metincansiper** [comment]
@ugurdogrusoz I handled all 3 items that you listed. However, for the second one ( It doesn't open up with the default network fit in window! (Windows 10, Chrome) ) the way I handled it may need to be improved. The problem was that the network container and some other components (e.g. the toolbar) are resized when the application is started and it is expected that the default sample is loaded after this resize end. However, this resize operation seems to be an asynchronous operation and so the default sample is loaded before it ends. I searched for the ways of listening an event triggered when this resize operation is ended but I could not found it. Therefore, I set a 100 ms timeout before I load the default sample.

**Comment by ugurdogrusoz** [comment]
4- Hitting expand/collapse clues are very difficult (need to click on lower right corner to actually hit them)

**Comment by ugurdogrusoz** [comment]
5- Layout won't return on attached model.

[TRAF3-dependent IRF activation pathway.sbgn.txt](https://github.com/iVis-at-Bilkent/sbgnviz.js-sample-app/files/633080/TRAF3-dependent.IRF.activation.pathway.sbgn.txt)

**Comment by ugurdogrusoz** [comment]
6- I think we should close all dialogs on Save (not related to refactoring but...)

**Comment by ugurdogrusoz** [comment]
7- Query > Pathway Commons > Paths Between...
   o fields too wide (both symbols and limit fields should be considerable shorter)
   o title should say "Paths Between Query"
   o when there is no symbol(s) entered, the query shouldn't be run

**Comment by ugurdogrusoz** [comment]
8- Hide/Show
   o Show Selected doesn't work
   o Show All doesn't work
   o Hide Selected works but cannot be undone

**Comment by ugurdogrusoz** [comment]
9- Help
   o Quick Help: Change "Right-click: Context menu for associated object"
   o About: space out content (more space between various parts of the content of the box) similar to old version

**Comment by ugurdogrusoz** [comment]
10- Legends: leave some paddings around the figures so the borders won't *touch* the figure

**Comment by ugurdogrusoz** [comment]
11- select the simple chemical inside synaptic vesicle and Hide Selected, see what happens to the compartment and the boundary of the outer compartment.

**Comment by metincansiper** [comment]
@ugurdogrusoz I made the bug fixes/improvements that you mentioned in general. However, some of them still seems to be problematic.

For #4, clicking expand/collapse clues are recognized by listening user click/tap events to related nodes. If s/he taps outside the node that action is not recognized.

For #5, I solve the main problem here and we do not have the old bug which is appearing on layout. It seems that layout returns now, but  the new problem is that it does not end properly and so the spinner(which starts with layout) do not disappear. This bug just occurs in this graph. I think that the problem is related to our modified cytoscape.js fork. Should we solve this bug in short term? If not maybe we can postpone it (Because I am not able to solve it yet).

For #11, previously our hide selected function was not performing as expected (As we talked today it should hide the nodes in a way that is smilar to 'delete selected smart'). I fixed it today and when we select that simple chemical and 'hide selected' then  synaptic vesicle is hidden as well and so the problem that you mentioned does not appear.
