### ISSUE TITLE
Spinner won't stop on layout

### ISSUE THREAD

**Issue by ugurdogrusoz** [iVis-at-Bilkent/sbgnviz.js-sample-app#2]
Spinner won't stop when a layout is performed on the following:
[TRAF3-dependent IRF activation pathway.sbgn.txt](https://github.com/iVis-at-Bilkent/sbgnviz.js-sample-app/files/633080/TRAF3-dependent.IRF.activation.pathway.sbgn.txt)

**Comment by ugurdogrusoz** [comment]
Easiest way to reproduce it to create a graph with only two disconnected nodes and calling layout. 
As per Metin, this is due to layout.stop() event is not triggered in such situations.

**Comment by metincansiper** [comment]
I moved tiling to l-level in cose bilkent in a branch called 'move-tiling-to-l-level-2 ' and used cose-bilkent from that branch in Newt temporarily so that you can test if there is any problem. It seems that this problem is solved now. If you also do not see any problem I will merge that branch in cose-bilkent and use cose-bilkent in Newt in the regular way.

**Comment by ugurdogrusoz** [comment]
Looks ok, let's please merge that branch to cose-bilkent.

**Comment by metincansiper** [comment]
I merged it in to cose bilkent.
